#Licensed under the MIT License.
#For details on the licensing terms, see the LICENSE file.
#SPDX-License-Identifier: MIT
#
#Copyright 2023-2024 (c) Fraunhofer IOSB (Author: Florian Düwel)

services:
  Dashboard:
    image: ghcr.io/swap-it/demo-scenario/dashboard:latest
    hostname: dashboard
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - swap_it_demo_scenario_network
  Execution_Engine:
    image: ghcr.io/swap-it/demo-scenario/execution-engine:beginner
    hostname: execution_engine
    expose:
      - 4000
    ports:
      - "4000:4000"
    networks:
      - swap_it_demo_scenario_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  swap_it_demo_scenario_network:
    driver: "bridge"
